"""Initial models

Revision ID: ff23233d9748
Revises:
Create Date: 2026-04-27 04:21:23.086148

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff23233d9748"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_project_name_not_empty"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "budget_at_completion", sa.Numeric(precision=15, scale=2), nullable=False
        ),
        sa.Column("planned_progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("actual_progress", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("actual_cost", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "actual_cost >= 0", name="ck_activity_actual_cost_non_negative"
        ),
        sa.CheckConstraint(
            "actual_progress >= 0 AND actual_progress <= 100",
            name="ck_activity_actual_progress_range",
        ),
        sa.CheckConstraint(
            "budget_at_completion >= 0", name="ck_activity_bac_non_negative"
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_activity_name_not_empty"),
        sa.CheckConstraint(
            "planned_progress >= 0 AND planned_progress <= 100",
            name="ck_activity_planned_progress_range",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activities_project_id", "activities", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activities_project_id", table_name="activities")
    op.drop_table("activities")
    op.drop_table("projects")
    # ### end Alembic commands ###
